var enumARRLRAC = {
    ME: "Maine",
    NH: "New Hampshire",
    VT: "Vermont",
    EMA: "Eastern Massachusetts",
    WMA: "Western Massachusetts",
    RI: "Rhode Island",
    CT: "Connecticut",
    NNY: "Northern New York",
    ENY: "Eastern New York",
    WNY: "Western New York",
    NLI: "New York City - Long Island",
    NNJ: "Northern New Jersey",
    SNJ: "Southern New Jersey",
    EPA: "Eastern Pennsylvania",
    WPA: "Western Pennsylvania",
    DE: "Delaware",
    MDC: "Maryland - DC",
    VA: "Virginia",
    KY: "Kentucky",
    TN: "Tennessee",
    NC: "North Carolina",
    SC: "South Carolina",
    GA: "Georgia",
    AL: "Alabama",
    NFL: "Northern Florida",
    WCF: "West Central Florida",
    SFL: "Southern Florida",
    MS: "Mississippi",
    AR: "Arkansas",
    LA: "Louisiana",
    NTX: "Northern Texas",
    STX: "Southern Texas",
    WTX: "Western Texas",
    OK: "Oklahoma",
    NM: "New Mexico",
    SV: "Sacramento Valley",
    SF: "San Francisco",
    EB: "East Bay",
    SCV: "Santa Clara Valley",
    SJV: "San Joaquin Valley",
    SB: "Santa Barbara",
    LAX: "Los Angeles",
    ORG: "Orange",
    SDG: "San Diego",
    WWA: "Western Washington",
    EWA: "Eastern Washington",
    OR: "Oregon",
    ID: "Idaho",
    NV: "Nevada",
    AZ: "Arizona",
    UT: "Utah",
    MT: "Montana",
    WY: "Wyoming",
    MI: "Michigan",
    OH: "Ohio",
    WV: "West Virginia",
    IN: "Indiana",
    IL: "Illinois",
    WI: "Wisconsin",
    MN: "Minnesota",
    IA: "Iowa",
    MO: "Missouri",
    KS: "Kansas",
    NE: "Nebraska",
    SD: "South Dakota",
    ND: "North Dakota",
    CO: "Colorado",
    AK: "Alaska",
    PAC: "Pacific",
    PR: "Puerto Rico",
    VI: "Virgin Islands",
    MAR: "Maritime",
    NL: "Newfoundland/Labrador",
    QC: "Quebec",
    ONE: "Ontario East",
    GTA: "Greater Toronto Area",
    ONS: "Ontario South",
    ONN: "Ontario North",
    MB: "Manitoba",
    SK: "Saskatchewan",
    AB: "Alberta",
    BC: "British Columbia",
    NT: "Northern Territories"
};

var enumDX = { DX: "DX" };
