CREATE DATABASE [DB_NAME];

CREATE USER '[DB_USER]'@'%' IDENTIFIED BY  '[DB_PASS]';

GRANT SELECT, INSERT, UPDATE, DELETE ON * . * TO  '[DB_USER]'@'%' IDENTIFIED BY  '[DB_PASS]' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
