CREATE TABLE master_list (
	contest_id      integer NOT NULL AUTO_INCREMENT,    
	contest_name_id integer unsigned NOT NULL,
    contest_date    date,
    callsign        varchar(10),
    x_data1         varchar(20),
    x_data2         varchar(20),
    x_data3         varchar(20),
    x_data4         varchar(20),
    x_data5         varchar(20),
    assisted_cat    varchar(15),
    band_cat        varchar(10),
    mode_cat        varchar(10),
    operator_cat    varchar(15),
    power_cat       varchar(10),
    station_cat     varchar(15),
    time_cat        varchar(15),
    transmitter_cat varchar(10),
    overlay_cat     varchar(20),
    location        varchar(10),
    claimed_score   integer,
    operators       varchar(100),
    club            varchar(50),
    name            varchar(50),
    address         varchar(255),
    addresscity     varchar(50),
    addressstate    varchar(5),
    addresszip      varchar(10),
    addresscountry  varchar(50),
    soapbox         text,
	PRIMARY KEY		(contest_id)
);
