CREATE USER 'sec_user'@'%' IDENTIFIED BY  '';

GRANT SELECT, INSERT, UPDATE, DELETE ON * . * TO  'sec_user'@'%' IDENTIFIED BY  '' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
